version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: opensaas-db
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: opensaas
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: opensaas-mail
    restart: always
    network_mode: host

volumes:
  postgres_data:
